inhibit_all_warnings!

target 'XLFBaseHttpRequestKitDemo' do
    
    platform :ios, '8.0'
    use_frameworks!

    pod 'XLFBaseHttpRequestKit_AFNetworking’, :git => 'https://github.com/MarkeJave/XLFBaseHttpRequestKit-AFNetworking.git', :tag => ‘1.0.2’
end
